name: CI

on: [push, pull_request]

jobs:
  package:
    name: ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux-64
            runner: ubuntu-24.04
          - platform: osx-arm64
            runner: macos-15

    steps:
      - uses: actions/checkout@v7.0.1
      - uses: prefix-dev/rattler-build-action@v0.2.39
        with:
          artifact-name: zeopp-lsmo-openmp-${{ matrix.platform }}
